#cloud-config
users: # Konfigurationen und Eigenschaften f端r die Users
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # User "ubuntu" bekommt "sudo-Berechtigungen" ohne Password eingeben zu m端ssen
    groups: users, admin # der User "ubuntu" wird in die Gruppen "users" & "admin" hinzugef端gt
    home: /home/ubuntu # Home Pfad
    shell: /bin/bash # Pfad f端r Standard-Shell
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key       
# SSH-Public Keys, die zugriff aufs User Konto haben, werden festlegt 
ssh_pwauth: false # die Passwortauthentifizierung ist deaktiviert 
disable_root: false # der Root-Benutzer ist nicht deaktiviert 
package_update: true # das System wird nach dem neustarten immer aktualisiert 
packages:
  - curl 
  - wget # Liste von packeges, die installiert sind
